### ISSUE TITLE
图床设置显示“暂无配置项”

### ISSUE THREAD

**Issue by Thomitics** [MoyuScript/picgo-plugin-superbed#1]
图床设置显示“暂无配置项”
![PicGo 103347](https://user-images.githubusercontent.com/62173814/121984244-39636a00-cdc5-11eb-9a50-4f7b2648ac7d.png)

**Comment by Passkou** [comment]
不清楚你怎么装的，我这和你版本一样倒是没问题，重装一下看看

![图片](https://user-images.githubusercontent.com/45550579/122019857-cd99f500-cdf6-11eb-935c-9fbd4b4e08d2.png)

**Comment by pengxiandyou** [comment]
我也是相同问题

**Comment by Passkou** [comment]
尝试升级到 1.0.1 版本试试，修了这个问题
